version: 1.0
jobs:
  test-job:
    artifacts:
      upload:
        - type: zip
          name: cache-test.zip
          location: stratus://pipeline-test-bucket/client
          regex:
            - '/catalyst/node_modules/**'
            - '/catalyst/package-lock.json'
    steps:
      - 'echo "Start: $(date)"'
      - npm i
      - 'echo "End: $(date)"'
      - ulimit -n 65536
stages:
  - name: build
    jobs:
      - test-job