version: 1.0
jobs:
  test-job:
    steps:
      - 'curl -L -o output.zip "https://pipeline-test-bucket-development.zohostratus.in/client/output.zip"'
      - unzip -q output.zip -d .
      - rm -rf output.zip
      - 'echo "Start: $(date)"'
      - npm i
      - 'echo "End: $(date)"'
stages:
  - name: build
    jobs:
      - test-job