version: 1.0
jobs:
  test-job:
    artifacts:
      upload:
        - type: file
          name: output.zip
          location: stratus://pipeline-test-bucket/client
          file: output.zip
    steps:
      - 'echo "Start: $(date)"'
      - npm i
      - 'echo "End: $(date)"'
      - zip -rq output.zip node_modules package-lock.json
      - ls
stages:
  - name: build
    jobs:
      - test-job