version: 1.0
jobs:
  test-job:
    artifacts:
      upload:
        - type: zip
          name: cache-test.zip
          location: stratus://pipeline-test-bucket/client
          regex:
            - 'node_modules/**'
    steps:
      - 'echo "Start: $(date)"'
      - npm i
      - 'echo "End: $(date)"'
stages:
  - name: build
    jobs:
      - test-job